#### This file contains the basic commands to create **Tensors** in Pytorch

---



In [1]:
import torch
print('Using torch', torch.__version__)

Using torch 2.1.0+cu118


In [2]:
#To have consistent results, let us set the seed to avoid randomness
torch.manual_seed(7)

In [3]:
#Initializing a random Torch Tensor
x = torch.Tensor(2,3)
print(x)

tensor([[4.2332e-02, 3.1993e-41, 0.0000e+00],
        [0.0000e+00, 7.7128e+31, 1.2737e-14]])


In [4]:
#Generating a ones tensor
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
#Generating a zeros tensor
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
#Generating a random tensor with uniformly distributed values between 0 and 1
torch.rand(3,2)

tensor([[0.5349, 0.1988],
        [0.6592, 0.6569],
        [0.2328, 0.4251]])

In [7]:
#Generating a random tensor with normally distributed values with mean 0 and variance 1
torch.randn(3,2)

tensor([[-1.2514, -1.8841],
        [ 0.4457, -0.7068],
        [-1.5750, -0.6318]])

In [8]:
#Creating a tensor from nested list
torch.Tensor([[1, 2],[3, 4]])

tensor([[1., 2.],
        [3., 4.]])

In [11]:
#Reshaping tensors
x = torch.arange(8)  #Create a Tensor
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [12]:
#Reshape the tensor using "View" method
x = x.view(2, 4)
print(x)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [13]:
#Swapping axes
x = x.permute(1, 0)
print(x)

tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])
