##### This file contains the basic commands of Pytorch

In [14]:
import numpy as np
import torch
print('Using torch', torch.__version__)

Using torch 2.1.0+cu118


In [2]:
#To have consistent results, let us set the seed to avoid randomness
torch.manual_seed(7)

In [3]:
#Initializing a random Torch Tensor
x = torch.Tensor(2,3)
print(x)

tensor([[8.4078e-45, 1.3563e-19, 6.9487e-17],
        [3.2355e-41, 6.9489e-17, 3.2355e-41]])


In [4]:
#Generating a ones tensor
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
#Generating a zeros tensor
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
#Generating a random tensor with uniformly distributed values between 0 and 1
torch.rand(3,2)

tensor([[0.5349, 0.1988],
        [0.6592, 0.6569],
        [0.2328, 0.4251]])

In [7]:
#Generating a random tensor with normally distributed values with mean 0 and variance 1
torch.randn(3,2)

tensor([[-1.2514, -1.8841],
        [ 0.4457, -0.7068],
        [-1.5750, -0.6318]])

In [8]:
#Creating a tensor from nested list
torch.Tensor([[1, 2],[3, 4]])

tensor([[1., 2.],
        [3., 4.]])

In [9]:
#Reshaping tensors
x = torch.arange(8)  #Create a Tensor
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [10]:
#Reshape the tensor using "View" method
x = x.view(2, 4)
print(x)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [11]:
#Swapping axes
x = x.permute(1, 0)
print(x)

tensor([[0, 4],
        [1, 5],
        [2, 6],
        [3, 7]])


In [12]:
#Converting Tensor to Numpy
x = torch.randn(2,3)
np_arr = x.numpy()

print(f'Tensor : {x}')
print(f'Numpy  : {np_arr}')

Tensor : tensor([[ 0.0212, -0.3602,  0.5662],
        [ 0.2142,  0.4963,  0.1196]])
Numpy  : [[ 0.02120138 -0.36019382  0.56623673]
 [ 0.21419007  0.49633223  0.11960004]]


In [16]:
#Converting Numpy to Tensor
np_arr = np.array([[1, 3],[5, 7]])
x = torch.from_numpy(np_arr)

print(f'Numpy  : {np_arr}')
print(f'Tensor : {x}')

Numpy  : [[1 3]
 [5 7]]
Tensor : tensor([[1, 3],
        [5, 7]])
