Here we show basic operations on Tensors

Adding two tensors

In [3]:
#Import needed libraries
import torch

In [4]:
x1 = torch.rand(3,4)
x2 = torch.rand(3,4)
y = x1 + x2

print(x1)
print(x2)
print(y)

tensor([[0.9773, 0.3834, 0.6051, 0.4778],
        [0.0264, 0.7212, 0.0707, 0.8574],
        [0.0242, 0.4377, 0.0043, 0.1323]])
tensor([[0.1896, 0.5361, 0.0823, 0.3939],
        [0.7779, 0.4281, 0.1918, 0.3582],
        [0.6110, 0.4582, 0.0525, 0.7042]])
tensor([[1.1669, 0.9194, 0.6875, 0.8717],
        [0.8043, 1.1492, 0.2625, 1.2156],
        [0.6352, 0.8959, 0.0568, 0.8365]])


In [5]:
#Inplace addition

print("Before Addition")
print(f"x1 = {x1}")
print(f"x2 = {x2}")

x2.add_(x1)
print("After Addition")
print(f"x1 = {x1}")
print(f"x2 = {x2}")

Before Addition
x1 = tensor([[0.9773, 0.3834, 0.6051, 0.4778],
        [0.0264, 0.7212, 0.0707, 0.8574],
        [0.0242, 0.4377, 0.0043, 0.1323]])
x2 = tensor([[0.1896, 0.5361, 0.0823, 0.3939],
        [0.7779, 0.4281, 0.1918, 0.3582],
        [0.6110, 0.4582, 0.0525, 0.7042]])
After Addition
x1 = tensor([[0.9773, 0.3834, 0.6051, 0.4778],
        [0.0264, 0.7212, 0.0707, 0.8574],
        [0.0242, 0.4377, 0.0043, 0.1323]])
x2 = tensor([[1.1669, 0.9194, 0.6875, 0.8717],
        [0.8043, 1.1492, 0.2625, 1.2156],
        [0.6352, 0.8959, 0.0568, 0.8365]])
