Here we show basic operations on Tensors

Adding two tensors

In [1]:
#Import needed libraries
import torch

In [2]:
x1 = torch.rand(3,4)
x2 = torch.rand(3,4)
y = x1 + x2

print(x1)
print(x2)
print(y)

tensor([[0.9624, 0.0743, 0.3133, 0.5535],
        [0.0042, 0.9842, 0.0819, 0.2553],
        [0.3432, 0.2221, 0.9092, 0.1059]])
tensor([[0.2217, 0.7624, 0.0643, 0.4502],
        [0.6941, 0.4877, 0.0740, 0.8787],
        [0.4898, 0.6303, 0.8442, 0.8855]])
tensor([[1.1841, 0.8367, 0.3776, 1.0037],
        [0.6983, 1.4719, 0.1559, 1.1340],
        [0.8330, 0.8524, 1.7534, 0.9915]])


In [3]:
#Inplace addition

print("Before Addition")
print(f"x1 = {x1}")
print(f"x2 = {x2}")

x2.add_(x1)
print("After Addition")
print(f"x1 = {x1}")
print(f"x2 = {x2}")

Before Addition
x1 = tensor([[0.9624, 0.0743, 0.3133, 0.5535],
        [0.0042, 0.9842, 0.0819, 0.2553],
        [0.3432, 0.2221, 0.9092, 0.1059]])
x2 = tensor([[0.2217, 0.7624, 0.0643, 0.4502],
        [0.6941, 0.4877, 0.0740, 0.8787],
        [0.4898, 0.6303, 0.8442, 0.8855]])
After Addition
x1 = tensor([[0.9624, 0.0743, 0.3133, 0.5535],
        [0.0042, 0.9842, 0.0819, 0.2553],
        [0.3432, 0.2221, 0.9092, 0.1059]])
x2 = tensor([[1.1841, 0.8367, 0.3776, 1.0037],
        [0.6983, 1.4719, 0.1559, 1.1340],
        [0.8330, 0.8524, 1.7534, 0.9915]])


Multiplying Tensors using different ways

In [4]:
#Initialize 1st Tensor
x1 = torch.arange(8)
x1 = x1.view(2, 4)
print(f'x1 = {x1}')

x1 = tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [5]:
#Initialize 2nd Tensor
x2 = torch.arange(12)
x2 = x2.view(4, 3)
print(f'x2 = {x2}')

x2 = tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [6]:
#Method 1
x3 = torch.matmul(x1, x2)
print(f'Size of x1 * x2 = {x3.shape}')
print(f'x1 * x2 = {x3}')

Size of x1 * x2 = torch.Size([2, 3])
x1 * x2 = tensor([[ 42,  48,  54],
        [114, 136, 158]])


In [7]:
#Method 2
x3 = x1@x2
print(f'Size of x1 * x2 = {x3.shape}')
print(f'x1 * x2 = {x3}')

Size of x1 * x2 = torch.Size([2, 3])
x1 * x2 = tensor([[ 42,  48,  54],
        [114, 136, 158]])
